[package]
name = "user/rbx-lag-compensated-hitbox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.0.9"
Promise = "evaera/promise@^3.1"
Signal = "sleitnick/signal@^1.0.0"
Janitor = "howmanysmall/janitor@^1.13"
